FROM ruby:2.3.1

RUN apt-get update && apt-get install -y nodejs build-essential qt5-default libqt5webkit5-dev iceweasel xvfb

RUN mkdir -p /app
WORKDIR /app

ADD Gemfile /app/Gemfile  
ADD Gemfile.lock /app/Gemfile.lock  
RUN bundle install

ADD . /app

CMD RAILS_ENV=test rake db:create db:migrate && xvfb-run rspec
