default: &default
  adapter:  postgresql
  database: <%= ENV["POSTGRES_DATABASE"] %>
  encoding: unicode
  username: <%= ENV["POSTGRES_USERNAME"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  pool:     <%= ENV["POSTGRES_POOL"] || 5 %>
  port:     <%= ENV["POSTGRES_PORT"] || 5432 %>
  host:     <%= ENV["POSTGRES_HOST"] %>

production:
  <<: *default
  database: mpal

development:
  <<: *default
  database: mpal

test:
  <<: *default
  database: mpal_test
